# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Hitter.create([{ :name => 'dummy value', :pos => 'x', :pos2 => '', :tm => 'x', :cost =>999, :selected =>false}])
Hitter.create([{ :name => 'Albert Pujols', :pos => '1B', :pos2 => '', :tm => 'SLN', :cost =>469, :selected =>true}])
Hitter.create([{ :name => 'Miguel Cabrera', :pos => '1B', :pos2 => '', :tm => 'DET', :cost =>387, :selected =>false}])
Hitter.create([{ :name => 'Hanley Ramirez', :pos => 'SS', :pos2 => '', :tm => 'FLO', :cost =>387, :selected =>true}])
Hitter.create([{ :name => 'Prince Fielder', :pos => '1B', :pos2 => '', :tm => 'MIL', :cost =>373, :selected =>true}])
Hitter.create([{ :name => 'Matt Holliday', :pos => 'OF', :pos2 => '', :tm => 'SLN', :cost =>352, :selected =>true}])
Hitter.create([{ :name => 'Ryan Braun', :pos => 'OF', :pos2 => '', :tm => 'MIL', :cost =>349, :selected =>false}])
Hitter.create([{ :name => 'Adrian Gonzalez', :pos => '1B', :pos2 => '', :tm => 'BOS', :cost =>346, :selected =>true}])
Hitter.create([{ :name => 'Mark Teixeira', :pos => '1B', :pos2 => '', :tm => 'NYA', :cost =>341, :selected =>false}])
Hitter.create([{ :name => 'David Wright', :pos => '3B', :pos2 => '', :tm => 'NYN', :cost =>328, :selected =>false}])
Hitter.create([{ :name => 'Joey Votto', :pos => '1B', :pos2 => '', :tm => 'CIN', :cost =>326, :selected =>false}])
Hitter.create([{ :name => 'Ryan Howard', :pos => '1B', :pos2 => '', :tm => 'PHI', :cost =>308, :selected =>false}])
Hitter.create([{ :name => 'Adam Dunn', :pos => '1B', :pos2 => '', :tm => 'CHA', :cost =>298, :selected =>false}])
Hitter.create([{ :name => 'Chase Utley', :pos => '2B', :pos2 => '', :tm => 'PHI', :cost =>296, :selected =>false}])
Hitter.create([{ :name => 'Alex Rodriguez', :pos => '3B', :pos2 => '', :tm => 'NYA', :cost =>288, :selected =>false}])
Hitter.create([{ :name => 'Joe Mauer', :pos => 'C', :pos2 => '', :tm => 'MIN', :cost =>274, :selected =>false}])
Hitter.create([{ :name => 'Troy Tulowitzki', :pos => 'SS', :pos2 => '', :tm => 'COL', :cost =>272, :selected =>false}])
Hitter.create([{ :name => 'Nick Markakis', :pos => 'OF', :pos2 => '', :tm => 'BAL', :cost =>271, :selected =>false}])
Hitter.create([{ :name => 'Kevin Youkilis', :pos => '1B', :pos2 => '', :tm => 'BOS', :cost =>257, :selected =>false}])
Hitter.create([{ :name => 'Derek Jeter', :pos => 'SS', :pos2 => '', :tm => 'NYA', :cost =>256, :selected =>false}])
Hitter.create([{ :name => 'Andrew McCutchen', :pos => 'OF', :pos2 => '', :tm => 'PIT', :cost =>256, :selected =>false}])
Hitter.create([{ :name => 'Robinson Cano', :pos => '2B', :pos2 => '', :tm => 'NYA', :cost =>255, :selected =>false}])
Hitter.create([{ :name => 'Ryan Zimmerman', :pos => '3B', :pos2 => '', :tm => 'WAS', :cost =>253, :selected =>false}])
Hitter.create([{ :name => 'Carlos Gonzalez', :pos => 'OF', :pos2 => '', :tm => 'COL', :cost =>253, :selected =>false}])
Hitter.create([{ :name => 'Carl Crawford', :pos => 'OF', :pos2 => '', :tm => 'BOS', :cost =>251, :selected =>false}])
Hitter.create([{ :name => 'Dan Uggla', :pos => '2B', :pos2 => '', :tm => 'ATL', :cost =>248, :selected =>false}])
Hitter.create([{ :name => 'Justin Morneau', :pos => '1B', :pos2 => '', :tm => 'MIN', :cost =>246, :selected =>false}])
Hitter.create([{ :name => 'Lance Berkman', :pos => '1B', :pos2 => '', :tm => 'SLN', :cost =>245, :selected =>false}])
Hitter.create([{ :name => 'Billy Butler', :pos => '1B', :pos2 => '', :tm => 'KCA', :cost =>244, :selected =>false}])
Hitter.create([{ :name => 'Ichiro Suzuki', :pos => 'OF', :pos2 => '', :tm => 'SEA', :cost =>243, :selected =>false}])
Hitter.create([{ :name => 'Michael Young', :pos => '3B', :pos2 => '', :tm => 'TEX', :cost =>238, :selected =>false}])
Hitter.create([{ :name => 'Pablo Sandoval', :pos => '3B', :pos2 => '', :tm => 'SFN', :cost =>235, :selected =>false}])
Hitter.create([{ :name => 'David Ortiz', :pos => '1B', :pos2 => '', :tm => 'BOS', :cost =>233, :selected =>false}])
Hitter.create([{ :name => 'Paul Konerko', :pos => '1B', :pos2 => '', :tm => 'CHA', :cost =>231, :selected =>false}])
Hitter.create([{ :name => 'Curtis Granderson', :pos => 'OF', :pos2 => '', :tm => 'NYA', :cost =>229, :selected =>false}])
Hitter.create([{ :name => 'Evan Longoria', :pos => '3B', :pos2 => '', :tm => 'TBA', :cost =>229, :selected =>false}])
Hitter.create([{ :name => 'Nick Swisher', :pos => 'OF', :pos2 => '', :tm => 'NYA', :cost =>221, :selected =>false}])
Hitter.create([{ :name => 'Kila Kaaihue', :pos => '1B', :pos2 => '', :tm => 'KCA', :cost =>221, :selected =>false}])
Hitter.create([{ :name => 'Denard Span', :pos => 'OF', :pos2 => '', :tm => 'MIN', :cost =>218, :selected =>false}])
Hitter.create([{ :name => 'Dustin Pedroia', :pos => '2B', :pos2 => '', :tm => 'BOS', :cost =>218, :selected =>false}])
Hitter.create([{ :name => 'Bobby Abreu', :pos => 'OF', :pos2 => '', :tm => 'ANA', :cost =>217, :selected =>false}])
Hitter.create([{ :name => 'Jimmy Rollins', :pos => 'SS', :pos2 => '', :tm => 'PHI', :cost =>214, :selected =>false}])
Hitter.create([{ :name => 'Todd Helton', :pos => '1B', :pos2 => '', :tm => 'COL', :cost =>212, :selected =>false}])
Hitter.create([{ :name => 'Brian Roberts', :pos => '2B', :pos2 => '', :tm => 'BAL', :cost =>208, :selected =>false}])
Hitter.create([{ :name => 'Chris Carter', :pos => '1B', :pos2 => '', :tm => 'OAK', :cost =>207, :selected =>false}])
Hitter.create([{ :name => 'Brandon Phillips', :pos => '2B', :pos2 => '', :tm => 'CIN', :cost =>205, :selected =>false}])
Hitter.create([{ :name => 'Vladimir Guerrero', :pos => 'OF', :pos2 => '', :tm => 'BAL', :cost =>205, :selected =>false}])
Hitter.create([{ :name => 'Matt Kemp', :pos => 'OF', :pos2 => '', :tm => 'LAN', :cost =>202, :selected =>false}])
Hitter.create([{ :name => 'Alex Rios', :pos => 'OF', :pos2 => '', :tm => 'CHA', :cost =>201, :selected =>false}])
Hitter.create([{ :name => 'Stephen Drew', :pos => 'SS', :pos2 => '', :tm => 'ARI', :cost =>200, :selected =>false}])
Hitter.create([{ :name => 'Jose Reyes', :pos => 'SS', :pos2 => '', :tm => 'NYN', :cost =>199, :selected =>false}])
Hitter.create([{ :name => 'Raul Ibanez', :pos => 'OF', :pos2 => '', :tm => 'PHI', :cost =>198, :selected =>false}])
Hitter.create([{ :name => 'Hunter Pence', :pos => 'OF', :pos2 => '', :tm => 'HOU', :cost =>197, :selected =>false}])
Hitter.create([{ :name => 'Jason Bay', :pos => 'OF', :pos2 => '', :tm => 'NYN', :cost =>197, :selected =>false}])
Hitter.create([{ :name => 'Nelson Cruz', :pos => 'OF', :pos2 => '', :tm => 'TEX', :cost =>195, :selected =>false}])
Hitter.create([{ :name => 'Andre Ethier', :pos => 'OF', :pos2 => '', :tm => 'LAN', :cost =>194, :selected =>false}])
Hitter.create([{ :name => 'Chris Young', :pos => 'OF', :pos2 => '', :tm => 'ARI', :cost =>193, :selected =>false}])
Hitter.create([{ :name => 'Ian Kinsler', :pos => '2B', :pos2 => '', :tm => 'TEX', :cost =>188, :selected =>false}])
Hitter.create([{ :name => 'Justin Upton', :pos => 'OF', :pos2 => '', :tm => 'ARI', :cost =>185, :selected =>false}])
Hitter.create([{ :name => 'Magglio Ordonez', :pos => 'OF', :pos2 => '', :tm => 'DET', :cost =>181, :selected =>false}])
Hitter.create([{ :name => 'Mark Reynolds', :pos => '3B', :pos2 => '', :tm => 'BAL', :cost =>180, :selected =>false}])
Hitter.create([{ :name => 'Jayson Werth', :pos => 'OF', :pos2 => '', :tm => 'WAS', :cost =>178, :selected =>false}])
Hitter.create([{ :name => 'Shane Victorino', :pos => 'OF', :pos2 => '', :tm => 'PHI', :cost =>178, :selected =>false}])
Hitter.create([{ :name => 'Kelly Johnson', :pos => '2B', :pos2 => '', :tm => 'ARI', :cost =>178, :selected =>false}])
Hitter.create([{ :name => 'Josh Hamilton', :pos => 'OF', :pos2 => '', :tm => 'TEX', :cost =>178, :selected =>false}])
Hitter.create([{ :name => 'Chipper Jones', :pos => '3B', :pos2 => '', :tm => 'ATL', :cost =>177, :selected =>false}])
Hitter.create([{ :name => 'Carlos Santana', :pos => 'C', :pos2 => '', :tm => 'CLE', :cost =>176, :selected =>false}])
Hitter.create([{ :name => 'Carlos Pena', :pos => '1B', :pos2 => '', :tm => 'CHN', :cost =>176, :selected =>false}])
Hitter.create([{ :name => 'Carlos Lee', :pos => 'OF', :pos2 => '', :tm => 'HOU', :cost =>176, :selected =>false}])
Hitter.create([{ :name => 'Alfonso Soriano', :pos => 'OF', :pos2 => '', :tm => 'CHN', :cost =>175, :selected =>false}])
Hitter.create([{ :name => 'Adrian Beltre', :pos => '3B', :pos2 => '', :tm => 'TEX', :cost =>175, :selected =>false}])
Hitter.create([{ :name => 'B.J. Upton', :pos => 'OF', :pos2 => '', :tm => 'TBA', :cost =>174, :selected =>false}])
Hitter.create([{ :name => 'Aubrey Huff', :pos => '1B', :pos2 => '', :tm => 'SFN', :cost =>174, :selected =>false}])
Hitter.create([{ :name => 'Derrek Lee', :pos => '1B', :pos2 => '', :tm => 'BAL', :cost =>173, :selected =>false}])
Hitter.create([{ :name => 'Johnny Damon', :pos => 'OF', :pos2 => '', :tm => 'TBA', :cost =>173, :selected =>false}])
Hitter.create([{ :name => 'Brian Mccann', :pos => 'C', :pos2 => '', :tm => 'ATL', :cost =>173, :selected =>false}])
Hitter.create([{ :name => 'Dexter Fowler', :pos => 'OF', :pos2 => '', :tm => 'COL', :cost =>171, :selected =>false}])
Hitter.create([{ :name => 'Grady Sizemore', :pos => 'OF', :pos2 => '', :tm => 'CLE', :cost =>171, :selected =>false}])
Hitter.create([{ :name => 'Pedro Alvarez', :pos => '3B', :pos2 => '', :tm => 'PIT', :cost =>169, :selected =>false}])
Hitter.create([{ :name => 'Victor Martinez', :pos => 'C', :pos2 => '', :tm => 'DET', :cost =>166, :selected =>false}])
Hitter.create([{ :name => 'James Loney', :pos => '1B', :pos2 => '', :tm => 'LAN', :cost =>164, :selected =>false}])
Hitter.create([{ :name => 'Chris Davis', :pos => '1B', :pos2 => '', :tm => 'TEX', :cost =>164, :selected =>false}])
Hitter.create([{ :name => 'Aramis Ramirez', :pos => '3B', :pos2 => '', :tm => 'CHN', :cost =>163, :selected =>false}])
Hitter.create([{ :name => 'Adam Laroche', :pos => '1B', :pos2 => '', :tm => 'WAS', :cost =>160, :selected =>false}])
Hitter.create([{ :name => 'Carlos Beltran', :pos => 'OF', :pos2 => '', :tm => 'NYN', :cost =>159, :selected =>false}])
Hitter.create([{ :name => 'Torii Hunter', :pos => 'OF', :pos2 => '', :tm => 'ANA', :cost =>159, :selected =>false}])
Hitter.create([{ :name => 'Jose Bautista', :pos => '3B', :pos2 => '', :tm => 'TOR', :cost =>158, :selected =>false}])
Hitter.create([{ :name => 'Michael Stanton', :pos => 'OF', :pos2 => '', :tm => 'FLO', :cost =>158, :selected =>false}])
Hitter.create([{ :name => 'Shin-Soo Choo', :pos => 'OF', :pos2 => '', :tm => 'CLE', :cost =>157, :selected =>false}])
Hitter.create([{ :name => 'Manny Ramirez', :pos => 'OF', :pos2 => '', :tm => 'TBA', :cost =>155, :selected =>false}])
Hitter.create([{ :name => 'Jason Heyward', :pos => 'OF', :pos2 => '', :tm => 'ATL', :cost =>155, :selected =>false}])
Hitter.create([{ :name => 'Dan Johnson', :pos => '1B', :pos2 => '', :tm => 'TBA', :cost =>152, :selected =>false}])
Hitter.create([{ :name => 'Jack Cust', :pos => 'OF', :pos2 => '', :tm => 'SEA', :cost =>145, :selected =>false}])
Hitter.create([{ :name => 'J.D. Drew', :pos => 'OF', :pos2 => '', :tm => 'BOS', :cost =>144, :selected =>false}])
Hitter.create([{ :name => 'Jay Bruce', :pos => 'OF', :pos2 => '', :tm => 'CIN', :cost =>144, :selected =>false}])
Hitter.create([{ :name => 'Chris Coghlan', :pos => 'OF', :pos2 => '', :tm => 'FLO', :cost =>142, :selected =>false}])
Hitter.create([{ :name => 'Jim Thome', :pos => 'DH', :pos2 => '', :tm => 'MIN', :cost =>142, :selected =>false}])
Hitter.create([{ :name => 'Juan Pierre', :pos => 'OF', :pos2 => '', :tm => 'CHA', :cost =>141, :selected =>false}])
Hitter.create([{ :name => 'Yunel Escobar', :pos => 'SS', :pos2 => '', :tm => 'TOR', :cost =>141, :selected =>false}])
Hitter.create([{ :name => 'Garrett Jones', :pos => '1B', :pos2 => '', :tm => 'PIT', :cost =>140, :selected =>false}])
Hitter.create([{ :name => 'Vernon Wells', :pos => 'OF', :pos2 => '', :tm => 'ANA', :cost =>138, :selected =>false}])
Hitter.create([{ :name => 'Chase Headley', :pos => 'OF', :pos2 => '', :tm => 'SDN', :cost =>138, :selected =>false}])
Hitter.create([{ :name => 'Russell Martin', :pos => 'C', :pos2 => '', :tm => 'NYA', :cost =>136, :selected =>false}])
Hitter.create([{ :name => 'Chone Figgins', :pos => '3B', :pos2 => '', :tm => 'SEA', :cost =>135, :selected =>false}])
Hitter.create([{ :name => 'Austin Jackson', :pos => 'OF', :pos2 => '', :tm => 'DET', :cost =>135, :selected =>false}])
Hitter.create([{ :name => 'Corey Hart', :pos => 'OF', :pos2 => '', :tm => 'MIL', :cost =>134, :selected =>false}])
Hitter.create([{ :name => 'Drew Stubbs', :pos => 'OF', :pos2 => '', :tm => 'CIN', :cost =>134, :selected =>false}])
Hitter.create([{ :name => 'Felipe Lopez', :pos => '2B', :pos2 => '', :tm => 'BOS', :cost =>133, :selected =>false}])
Hitter.create([{ :name => 'Adam Lind', :pos => 'OF', :pos2 => '', :tm => 'TOR', :cost =>133, :selected =>false}])
Hitter.create([{ :name => 'Jose Lopez', :pos => '2B', :pos2 => '', :tm => 'COL', :cost =>133, :selected =>false}])
Hitter.create([{ :name => 'Jhonny Peralta', :pos => 'SS', :pos2 => '', :tm => 'DET', :cost =>133, :selected =>false}])
Hitter.create([{ :name => 'Luke Scott', :pos => 'OF', :pos2 => '', :tm => 'BAL', :cost =>131, :selected =>false}])
Hitter.create([{ :name => 'Kosuke Fukudome', :pos => 'OF', :pos2 => '', :tm => 'CHN', :cost =>131, :selected =>false}])
Hitter.create([{ :name => 'Brad Hawpe', :pos => 'OF', :pos2 => '', :tm => 'SDN', :cost =>129, :selected =>false}])
Hitter.create([{ :name => 'Gaby Sanchez', :pos => '1B', :pos2 => '', :tm => 'FLO', :cost =>129, :selected =>false}])
Hitter.create([{ :name => 'Orlando Cabrera', :pos => 'SS', :pos2 => '', :tm => 'CLE', :cost =>128, :selected =>false}])
Hitter.create([{ :name => 'Ian Stewart', :pos => '3B', :pos2 => '', :tm => 'COL', :cost =>127, :selected =>false}])
Hitter.create([{ :name => 'Miguel Tejada', :pos => 'SS', :pos2 => '', :tm => 'SFN', :cost =>126, :selected =>false}])
Hitter.create([{ :name => 'Michael Cuddyer', :pos => 'OF', :pos2 => '', :tm => 'MIN', :cost =>126, :selected =>false}])
Hitter.create([{ :name => 'Alexei Ramirez', :pos => 'SS', :pos2 => '', :tm => 'CHA', :cost =>125, :selected =>false}])
Hitter.create([{ :name => 'Marlon Byrd', :pos => 'OF', :pos2 => '', :tm => 'CHN', :cost =>124, :selected =>false}])
Hitter.create([{ :name => 'Logan Morrison', :pos => '1B', :pos2 => '', :tm => 'FLO', :cost =>120, :selected =>false}])
Hitter.create([{ :name => 'Michael Brantley', :pos => 'OF', :pos2 => '', :tm => 'CLE', :cost =>119, :selected =>false}])
Hitter.create([{ :name => 'Cliff Pennington', :pos => 'SS', :pos2 => '', :tm => 'OAK', :cost =>119, :selected =>false}])
Hitter.create([{ :name => 'Jacoby Ellsbury', :pos => 'OF', :pos2 => '', :tm => 'BOS', :cost =>118, :selected =>false}])
Hitter.create([{ :name => 'Jeff Francoeur', :pos => 'OF', :pos2 => '', :tm => 'KCA', :cost =>118, :selected =>false}])
Hitter.create([{ :name => 'Placido Polanco', :pos => '2B', :pos2 => '', :tm => 'PHI', :cost =>116, :selected =>false}])
Hitter.create([{ :name => 'Casey McGehee', :pos => '3B', :pos2 => '', :tm => 'MIL', :cost =>114, :selected =>false}])
Hitter.create([{ :name => 'Lyle Overbay', :pos => '1B', :pos2 => '', :tm => 'PIT', :cost =>114, :selected =>false}])
Hitter.create([{ :name => 'Nolan Reimold', :pos => 'OF', :pos2 => '', :tm => 'BAL', :cost =>113, :selected =>false}])
Hitter.create([{ :name => 'Pat Burrell', :pos => 'OF', :pos2 => '', :tm => 'SFN', :cost =>110, :selected =>false}])
Hitter.create([{ :name => 'Elvis Andrus', :pos => 'SS', :pos2 => '', :tm => 'TEX', :cost =>110, :selected =>false}])
Hitter.create([{ :name => 'Ryan Theriot', :pos => 'SS', :pos2 => '', :tm => 'SLN', :cost =>109, :selected =>false}])
Hitter.create([{ :name => 'Delmon Young', :pos => 'OF', :pos2 => '', :tm => 'MIN', :cost =>107, :selected =>false}])
Hitter.create([{ :name => 'Josh Willingham', :pos => 'OF', :pos2 => '', :tm => 'OAK', :cost =>105, :selected =>false}])
Hitter.create([{ :name => 'Geovany Soto', :pos => 'C', :pos2 => '', :tm => 'CHN', :cost =>104, :selected =>false}])
Hitter.create([{ :name => 'Rafael Furcal', :pos => 'SS', :pos2 => '', :tm => 'LAN', :cost =>104, :selected =>false}])
Hitter.create([{ :name => 'David Dejesus', :pos => 'OF', :pos2 => '', :tm => 'OAK', :cost =>104, :selected =>false}])
Hitter.create([{ :name => 'Carlos Quentin', :pos => 'OF', :pos2 => '', :tm => 'CHA', :cost =>103, :selected =>false}])
Hitter.create([{ :name => 'Matt Wieters', :pos => 'C', :pos2 => '', :tm => 'BAL', :cost =>102, :selected =>false}])
Hitter.create([{ :name => 'Brett Gardner', :pos => 'OF', :pos2 => '', :tm => 'NYA', :cost =>101, :selected =>false}])
Hitter.create([{ :name => 'Seth Smith', :pos => 'OF', :pos2 => '', :tm => 'COL', :cost =>100, :selected =>false}])
Hitter.create([{ :name => 'Julio Borbon', :pos => 'OF', :pos2 => '', :tm => 'TEX', :cost =>95, :selected =>false}])
Hitter.create([{ :name => 'David Murphy', :pos => 'OF', :pos2 => '', :tm => 'TEX', :cost =>94, :selected =>false}])
Hitter.create([{ :name => 'Scott Rolen', :pos => '3B', :pos2 => '', :tm => 'CIN', :cost =>93, :selected =>false}])
Hitter.create([{ :name => 'Freddy Sanchez', :pos => '2B', :pos2 => '', :tm => 'SFN', :cost =>93, :selected =>false}])
Hitter.create([{ :name => 'Asdrubal Cabrera', :pos => 'SS', :pos2 => '', :tm => 'CLE', :cost =>92, :selected =>false}])
Hitter.create([{ :name => 'Aaron Hill', :pos => '2B', :pos2 => '', :tm => 'TOR', :cost =>92, :selected =>false}])
Hitter.create([{ :name => 'Ryan Ludwick', :pos => 'OF', :pos2 => '', :tm => 'SDN', :cost =>92, :selected =>false}])
Hitter.create([{ :name => 'Orlando Hudson', :pos => '2B', :pos2 => '', :tm => 'SDN', :cost =>90, :selected =>false}])
Hitter.create([{ :name => 'Rickie Weeks', :pos => '2B', :pos2 => '', :tm => 'MIL', :cost =>89, :selected =>false}])
Hitter.create([{ :name => 'Alcides Escobar', :pos => 'SS', :pos2 => '', :tm => 'KCA', :cost =>89, :selected =>false}])
Hitter.create([{ :name => 'Allen Craig', :pos => 'OF', :pos2 => '', :tm => 'SLN', :cost =>87, :selected =>false}])
Hitter.create([{ :name => 'Melky Cabrera', :pos => 'OF', :pos2 => '', :tm => 'KCA', :cost =>87, :selected =>false}])
Hitter.create([{ :name => 'Buster Posey', :pos => 'C', :pos2 => '', :tm => 'SFN', :cost =>85, :selected =>false}])
Hitter.create([{ :name => 'Ty Wigginton', :pos => '3B', :pos2 => '', :tm => 'COL', :cost =>84, :selected =>false}])
Hitter.create([{ :name => 'Adam Jones', :pos => 'OF', :pos2 => '', :tm => 'BAL', :cost =>84, :selected =>false}])
Hitter.create([{ :name => 'Casey Blake', :pos => '3B', :pos2 => '', :tm => 'LAN', :cost =>82, :selected =>false}])
Hitter.create([{ :name => 'Jason Bartlett', :pos => 'SS', :pos2 => '', :tm => 'SDN', :cost =>80, :selected =>false}])
Hitter.create([{ :name => 'Jason Kubel', :pos => 'OF', :pos2 => '', :tm => 'MIN', :cost =>79, :selected =>false}])
Hitter.create([{ :name => 'Chris Iannetta', :pos => 'C', :pos2 => '', :tm => 'COL', :cost =>78, :selected =>false}])
Hitter.create([{ :name => 'Edwin Encarnacion', :pos => '3B', :pos2 => '', :tm => 'TOR', :cost =>78, :selected =>false}])
Hitter.create([{ :name => 'Jorge Cantu', :pos => '3B', :pos2 => '', :tm => 'TEX', :cost =>75, :selected =>false}])
Hitter.create([{ :name => 'Mike Cameron', :pos => 'OF', :pos2 => '', :tm => 'BOS', :cost =>73, :selected =>false}])
Hitter.create([{ :name => 'Martin Prado', :pos => '2B', :pos2 => '', :tm => 'ATL', :cost =>72, :selected =>false}])
Hitter.create([{ :name => 'Marco Scutaro', :pos => 'SS', :pos2 => '', :tm => 'BOS', :cost =>71, :selected =>false}])
Hitter.create([{ :name => 'Travis Hafner', :pos => 'DH', :pos2 => '', :tm => 'CLE', :cost =>70, :selected =>false}])
Hitter.create([{ :name => 'Neil Walker', :pos => '3B', :pos2 => '', :tm => 'PIT', :cost =>68, :selected =>false}])
Hitter.create([{ :name => 'Gerardo Parra', :pos => 'OF', :pos2 => '', :tm => 'ARI', :cost =>67, :selected =>false}])
Hitter.create([{ :name => 'Mark Teahen', :pos => '3B', :pos2 => '', :tm => 'CHA', :cost =>66, :selected =>false}])
Hitter.create([{ :name => 'Matt LaPorta', :pos => '1B', :pos2 => '', :tm => 'CLE', :cost =>65, :selected =>false}])
Hitter.create([{ :name => 'Skip Schumaker', :pos => '2B', :pos2 => '', :tm => 'SLN', :cost =>62, :selected =>false}])
Hitter.create([{ :name => 'Travis Snider', :pos => 'OF', :pos2 => '', :tm => 'TOR', :cost =>60, :selected =>false}])
Hitter.create([{ :name => 'Mike Lowell', :pos => '3B', :pos2 => '', :tm => 'BOS', :cost =>60, :selected =>false}])
Hitter.create([{ :name => 'Blake DeWitt', :pos => '2B', :pos2 => '', :tm => 'CHN', :cost =>58, :selected =>false}])
Hitter.create([{ :name => 'Jose Tabata', :pos => 'OF', :pos2 => '', :tm => 'PIT', :cost =>57, :selected =>false}])
Hitter.create([{ :name => 'Will Venable', :pos => 'OF', :pos2 => '', :tm => 'SDN', :cost =>55, :selected =>false}])
Hitter.create([{ :name => 'Carlos Guillen', :pos => '3B', :pos2 => '', :tm => 'DET', :cost =>54, :selected =>false}])
Hitter.create([{ :name => 'Colby Rasmus', :pos => 'OF', :pos2 => '', :tm => 'SLN', :cost =>53, :selected =>false}])
Hitter.create([{ :name => 'Domonic Brown', :pos => 'OF', :pos2 => '', :tm => 'PHI', :cost =>51, :selected =>false}])
Hitter.create([{ :name => 'Nate McLouth', :pos => 'OF', :pos2 => '', :tm => 'ATL', :cost =>51, :selected =>false}])
Hitter.create([{ :name => 'Melvin Mora', :pos => '3B', :pos2 => '', :tm => 'ARI', :cost =>50, :selected =>false}])
Hitter.create([{ :name => 'Jorge Posada', :pos => 'C', :pos2 => '', :tm => 'NYA', :cost =>50, :selected =>false}])
Hitter.create([{ :name => 'Kendry Morales', :pos => '1B', :pos2 => '', :tm => 'ANA', :cost =>49, :selected =>false}])
Hitter.create([{ :name => 'Kurt Suzuki', :pos => 'C', :pos2 => '', :tm => 'OAK', :cost =>43, :selected =>false}])
Hitter.create([{ :name => 'Mike Napoli', :pos => 'C', :pos2 => '', :tm => 'TEX', :cost =>42, :selected =>false}])
Hitter.create([{ :name => 'Peter Bourjos', :pos => 'OF', :pos2 => '', :tm => 'ANA', :cost =>41, :selected =>false}])
Hitter.create([{ :name => 'Miguel Montero', :pos => 'C', :pos2 => '', :tm => 'ARI', :cost =>40, :selected =>false}])
Hitter.create([{ :name => 'Ryan Raburn', :pos => 'OF', :pos2 => '', :tm => 'DET', :cost =>40, :selected =>false}])
Hitter.create([{ :name => 'Frederick Freeman', :pos => '1B', :pos2 => '', :tm => 'ATL', :cost =>38, :selected =>false}])
Hitter.create([{ :name => 'Will Rhymes', :pos => '2B', :pos2 => '', :tm => 'DET', :cost =>37, :selected =>false}])
Hitter.create([{ :name => 'Juan Miranda', :pos => '1B', :pos2 => '', :tm => 'ARI', :cost =>35, :selected =>false}])
Hitter.create([{ :name => 'Cameron Maybin', :pos => 'OF', :pos2 => '', :tm => 'SDN', :cost =>32, :selected =>false}])
Hitter.create([{ :name => 'Mike Jacobs', :pos => '1B', :pos2 => '', :tm => 'TOR', :cost =>31, :selected =>false}])
Hitter.create([{ :name => 'Mike Morse', :pos => 'OF', :pos2 => '', :tm => 'WAS', :cost =>31, :selected =>false}])
Hitter.create([{ :name => 'Brennan Boesch', :pos => 'OF', :pos2 => '', :tm => 'DET', :cost =>31, :selected =>false}])
Hitter.create([{ :name => 'Howie Kendrick', :pos => '2B', :pos2 => '', :tm => 'ANA', :cost =>30, :selected =>false}])
Hitter.create([{ :name => 'Fred Lewis', :pos => 'OF', :pos2 => '', :tm => 'CIN', :cost =>29, :selected =>false}])
Hitter.create([{ :name => 'Kevin Kouzmanoff', :pos => '3B', :pos2 => '', :tm => 'OAK', :cost =>28, :selected =>false}])
Hitter.create([{ :name => 'Carlos Ruiz', :pos => 'C', :pos2 => '', :tm => 'PHI', :cost =>27, :selected =>false}])
Hitter.create([{ :name => 'Angel Pagan', :pos => 'OF', :pos2 => '', :tm => 'NYN', :cost =>27, :selected =>false}])
Hitter.create([{ :name => 'Andres Torres', :pos => 'OF', :pos2 => '', :tm => 'SFN', :cost =>27, :selected =>false}])
Hitter.create([{ :name => 'Ryan Hanigan', :pos => 'C', :pos2 => '', :tm => 'CIN', :cost =>26, :selected =>false}])
Hitter.create([{ :name => 'Yuniesky Betancourt', :pos => 'SS', :pos2 => '', :tm => 'MIL', :cost =>25, :selected =>false}])
Hitter.create([{ :name => 'Brandon Inge', :pos => '3B', :pos2 => '', :tm => 'DET', :cost =>24, :selected =>false}])
Hitter.create([{ :name => 'Rajai Davis', :pos => 'OF', :pos2 => '', :tm => 'TOR', :cost =>24, :selected =>false}])
Hitter.create([{ :name => 'Nyjer Morgan', :pos => 'OF', :pos2 => '', :tm => 'WAS', :cost =>24, :selected =>false}])
Hitter.create([{ :name => 'Edgar Renteria', :pos => 'SS', :pos2 => '', :tm => 'SFN', :cost =>23, :selected =>false}])
Hitter.create([{ :name => 'Daniel Murphy', :pos => '1B', :pos2 => '', :tm => 'NYN', :cost =>23, :selected =>false}])
Hitter.create([{ :name => 'Ike Davis', :pos => '1B', :pos2 => '', :tm => 'NYN', :cost =>22, :selected =>false}])
Hitter.create([{ :name => 'Omar Infante', :pos => '2B', :pos2 => '', :tm => 'FLO', :cost =>22, :selected =>false}])
Hitter.create([{ :name => 'Tyler Colvin', :pos => 'OF', :pos2 => '', :tm => 'CHN', :cost =>21, :selected =>false}])
Hitter.create([{ :name => 'Milton Bradley', :pos => 'OF', :pos2 => '', :tm => 'SEA', :cost =>20, :selected =>false}])
Hitter.create([{ :name => 'Coco Crisp', :pos => 'OF', :pos2 => '', :tm => 'OAK', :cost =>20, :selected =>false}])
Hitter.create([{ :name => 'David Freese', :pos => '3B', :pos2 => '', :tm => 'SLN', :cost =>19, :selected =>false}])
Hitter.create([{ :name => 'Ben Francisco', :pos => 'OF', :pos2 => '', :tm => 'PHI', :cost =>19, :selected =>false}])
Hitter.create([{ :name => 'Luis Castillo', :pos => '2B', :pos2 => '', :tm => 'NYN', :cost =>19, :selected =>false}])
Hitter.create([{ :name => 'A.J. Pierzynski', :pos => 'C', :pos2 => '', :tm => 'CHA', :cost =>19, :selected =>false}])
Hitter.create([{ :name => 'Luis Valbuena', :pos => '2B', :pos2 => '', :tm => 'CLE', :cost =>18, :selected =>false}])
Hitter.create([{ :name => 'Jed Lowrie', :pos => 'SS', :pos2 => '', :tm => 'BOS', :cost =>17, :selected =>false}])
Hitter.create([{ :name => 'Yadier Molina', :pos => 'C', :pos2 => '', :tm => 'SLN', :cost =>17, :selected =>false}])
Hitter.create([{ :name => 'Dallas McPherson', :pos => '3B', :pos2 => '', :tm => 'OAK', :cost =>16, :selected =>false}])
Hitter.create([{ :name => 'Gordon Beckham', :pos => '2B', :pos2 => '', :tm => 'CHA', :cost =>16, :selected =>false}])
Hitter.create([{ :name => 'Jonny Gomes', :pos => 'OF', :pos2 => '', :tm => 'CIN', :cost =>14, :selected =>false}])
Hitter.create([{ :name => 'J.J. Hardy', :pos => 'SS', :pos2 => '', :tm => 'BAL', :cost =>12, :selected =>false}])
Hitter.create([{ :name => 'John Mayberry', :pos => 'OF', :pos2 => '', :tm => 'PHI', :cost =>11, :selected =>false}])
Hitter.create([{ :name => 'Jay Gibbons', :pos => 'OF', :pos2 => '', :tm => 'LAN', :cost =>11, :selected =>false}])
Hitter.create([{ :name => 'Brent Morel', :pos => '3B', :pos2 => '', :tm => 'CHA', :cost =>10, :selected =>false}])
Hitter.create([{ :name => 'Starlin Castro', :pos => 'SS', :pos2 => '', :tm => 'CHN', :cost =>10, :selected =>false}])
Hitter.create([{ :name => 'Matt Diaz', :pos => 'OF', :pos2 => '', :tm => 'PIT', :cost =>10, :selected =>false}])
Hitter.create([{ :name => 'Roger Bernadina', :pos => 'OF', :pos2 => '', :tm => 'WAS', :cost =>10, :selected =>false}])
Hitter.create([{ :name => 'Ian Desmond', :pos => 'SS', :pos2 => '', :tm => 'WAS', :cost =>10, :selected =>false}])
Hitter.create([{ :name => 'Scott Sizemore', :pos => '2B', :pos2 => '', :tm => 'DET', :cost =>9, :selected =>false}])
Hitter.create([{ :name => 'Sean Rodriguez', :pos => '2B', :pos2 => '', :tm => 'TBA', :cost =>7, :selected =>false}])
Hitter.create([{ :name => 'Cody Ross', :pos => 'OF', :pos2 => '', :tm => 'SFN', :cost =>7, :selected =>false}])
Hitter.create([{ :name => 'Juan Rivera', :pos => 'OF', :pos2 => '', :tm => 'TOR', :cost =>7, :selected =>false}])
Hitter.create([{ :name => 'John Jaso', :pos => 'C', :pos2 => '', :tm => 'TBA', :cost =>5, :selected =>false}])
Hitter.create([{ :name => 'Mark Ellis', :pos => '2B', :pos2 => '', :tm => 'OAK', :cost =>4, :selected =>false}])
Hitter.create([{ :name => 'Chris Johnson', :pos => '3B', :pos2 => '', :tm => 'HOU', :cost =>3, :selected =>false}])
Hitter.create([{ :name => 'Ryan Doumit', :pos => 'C', :pos2 => '', :tm => 'PIT', :cost =>3, :selected =>false}])
Hitter.create([{ :name => 'Justin Smoak', :pos => '1B', :pos2 => '', :tm => 'SEA', :cost =>3, :selected =>false}])
Hitter.create([{ :name => 'Juan Uribe', :pos => 'SS', :pos2 => '', :tm => 'LAN', :cost =>2, :selected =>false}])
Hitter.create([{ :name => 'Mike Aviles', :pos => 'SS', :pos2 => '', :tm => 'KCA', :cost =>1, :selected =>false}])
Hitter.create([{ :name => 'Maicer Izturis', :pos => '2B', :pos2 => '', :tm => 'ANA', :cost =>1, :selected =>false}])
Hitter.create([{ :name => 'Chris Getz', :pos => '2B', :pos2 => '', :tm => 'KCA', :cost =>1, :selected =>false}])
Hitter.create([{ :name => 'Clint Barmes', :pos => '2B', :pos2 => '', :tm => 'HOU', :cost =>1, :selected =>false}])
Hitter.create([{ :name => 'Jayson Nix', :pos => '2B', :pos2 => '', :tm => 'CLE', :cost =>1, :selected =>false}])
Hitter.create([{ :name => 'Alexi Casilla', :pos => '2B', :pos2 => '', :tm => 'MIN', :cost =>1, :selected =>false}])
Hitter.create([{ :name => 'Matt Dominguez', :pos => '3B', :pos2 => '', :tm => 'FLO', :cost =>1, :selected =>false}])
Hitter.create([{ :name => 'Wilson Betemit', :pos => '3B', :pos2 => '', :tm => 'KCA', :cost =>1, :selected =>false}])
Hitter.create([{ :name => 'Brett Wallace', :pos => '3B', :pos2 => '', :tm => 'HOU', :cost =>1, :selected =>false}])
Hitter.create([{ :name => 'Bill Hall', :pos => '3B', :pos2 => '', :tm => 'HOU', :cost =>1, :selected =>false}])
Hitter.create([{ :name => 'Wes Helms', :pos => '3B', :pos2 => '', :tm => 'FLO', :cost =>1, :selected =>false}])
Hitter.create([{ :name => 'George Kottaras', :pos => 'C', :pos2 => '', :tm => 'MIL', :cost =>1, :selected =>false}])
Hitter.create([{ :name => 'Chris Snyder', :pos => 'C', :pos2 => '', :tm => 'PIT', :cost =>1, :selected =>false}])
Hitter.create([{ :name => 'Angel Salome', :pos => 'C', :pos2 => '', :tm => 'MIL', :cost =>1, :selected =>false}])
Hitter.create([{ :name => 'Ramon Hernandez', :pos => 'C', :pos2 => '', :tm => 'CIN', :cost =>1, :selected =>false}])
Hitter.create([{ :name => 'Ramon Castro', :pos => 'C', :pos2 => '', :tm => 'CHA', :cost =>1, :selected =>false}])
Hitter.create([{ :name => 'Josh Thole', :pos => 'C', :pos2 => '', :tm => 'NYN', :cost =>1, :selected =>false}])
Hitter.create([{ :name => 'Yorvit Torrealba', :pos => 'C', :pos2 => '', :tm => 'TEX', :cost =>1, :selected =>false}])
Hitter.create([{ :name => 'Bengie Molina', :pos => 'C', :pos2 => '', :tm => 'TEX', :cost =>1, :selected =>false}])
Hitter.create([{ :name => 'Alex Avila', :pos => 'C', :pos2 => '', :tm => 'DET', :cost =>1, :selected =>false}])
Hitter.create([{ :name => 'Jason Kendall', :pos => 'C', :pos2 => '', :tm => 'KCA', :cost =>1, :selected =>false}])
Hitter.create([{ :name => 'John Buck', :pos => 'C', :pos2 => '', :tm => 'FLO', :cost =>1, :selected =>false}])
Hitter.create([{ :name => 'Ronny Paulino', :pos => 'C', :pos2 => '', :tm => 'NYN', :cost =>1, :selected =>false}])
Hitter.create([{ :name => 'Jarrod Saltalamacchia', :pos => 'C', :pos2 => '', :tm => 'BOS', :cost =>1, :selected =>false}])
Hitter.create([{ :name => 'Jason Castro', :pos => 'C', :pos2 => '', :tm => 'HOU', :cost =>1, :selected =>false}])
Hitter.create([{ :name => 'Miguel Olivo', :pos => 'C', :pos2 => '', :tm => 'SEA', :cost =>1, :selected =>false}])
Hitter.create([{ :name => 'Nick Hundley', :pos => 'C', :pos2 => '', :tm => 'SDN', :cost =>1, :selected =>false}])
Hitter.create([{ :name => 'Adam Moore', :pos => 'C', :pos2 => '', :tm => 'SEA', :cost =>1, :selected =>false}])
Hitter.create([{ :name => 'Wilson Ramos', :pos => 'C', :pos2 => '', :tm => 'WAS', :cost =>1, :selected =>false}])
Hitter.create([{ :name => 'Ivan Rodriguez', :pos => 'C', :pos2 => '', :tm => 'WAS', :cost =>1, :selected =>false}])
Hitter.create([{ :name => 'Rod Barajas', :pos => 'C', :pos2 => '', :tm => 'LAN', :cost =>1, :selected =>false}])
Hitter.create([{ :name => 'Jeff Mathis', :pos => 'C', :pos2 => '', :tm => 'ANA', :cost =>1, :selected =>false}])
Hitter.create([{ :name => 'Laynce Nix', :pos => 'OF', :pos2 => '', :tm => 'CIN', :cost =>1, :selected =>false}])
Hitter.create([{ :name => 'Marcus Thames', :pos => 'OF', :pos2 => '', :tm => 'LAN', :cost =>1, :selected =>false}])
Hitter.create([{ :name => 'Rick Ankiel', :pos => 'OF', :pos2 => '', :tm => 'WAS', :cost =>1, :selected =>false}])
Hitter.create([{ :name => 'Tony Gwynn', :pos => 'OF', :pos2 => '', :tm => 'LAN', :cost =>1, :selected =>false}])
Hitter.create([{ :name => 'Carlos Gomez', :pos => 'OF', :pos2 => '', :tm => 'MIL', :cost =>1, :selected =>false}])
Hitter.create([{ :name => 'Danny Espinosa', :pos => 'SS', :pos2 => '', :tm => 'WAS', :cost =>1, :selected =>false}])
Hitter.create([{ :name => 'Alex Gonzalez', :pos => 'SS', :pos2 => '', :tm => 'ATL', :cost =>1, :selected =>false}])
Hitter.create([{ :name => 'Brandon Wood', :pos => 'SS', :pos2 => '', :tm => 'ANA', :cost =>1, :selected =>false}])
Hitter.create([{ :name => 'Jason Donald', :pos => 'SS', :pos2 => '', :tm => 'CLE', :cost =>1, :selected =>false}])
Hitter.create([{ :name => 'Paul Janish', :pos => 'SS', :pos2 => '', :tm => 'CIN', :cost =>1, :selected =>false}])
Hitter.create([{ :name => 'Ronny Cedeno', :pos => 'SS', :pos2 => '', :tm => 'PIT', :cost =>1, :selected =>false}])
Hitter.create([{ :name => 'Erick Aybar', :pos => 'SS', :pos2 => '', :tm => 'ANA', :cost =>1, :selected =>false}])
Hitter.create([{ :name => 'Ruben Tejada', :pos => 'SS', :pos2 => '', :tm => 'NYN', :cost =>1, :selected =>false}])
Hitter.create([{ :name => 'Reid Brignac', :pos => 'SS', :pos2 => '', :tm => 'TBA', :cost =>1, :selected =>false}])
Hitter.create([{ :name => 'Jack Wilson', :pos => 'SS', :pos2 => '', :tm => 'SEA', :cost =>1, :selected =>false}])
Pitcher.create([{ :name => 'dummy value', :pos => 'x', :tm => 'x', :cost =>999, :selected =>false}])
Pitcher.create([{ :name => 'Felix Hernandez', :pos => 'SP', :tm => 'SEA', :cost =>491, :selected =>true}])
Pitcher.create([{ :name => 'Roy Halladay', :pos => 'SP', :tm => 'PHI', :cost =>464, :selected =>true}])
Pitcher.create([{ :name => 'Dan Haren', :pos => 'SP', :tm => 'ANA', :cost =>425, :selected =>true}])
Pitcher.create([{ :name => 'Tim Lincecum', :pos => 'SP', :tm => 'SFN', :cost =>399, :selected =>true}])
Pitcher.create([{ :name => 'CC Sabathia', :pos => 'SP', :tm => 'NYA', :cost =>395, :selected =>true}])
Pitcher.create([{ :name => 'Cliff Lee', :pos => 'SP', :tm => 'PHI', :cost =>388, :selected =>false}])
Pitcher.create([{ :name => 'Johan Santana', :pos => 'SP', :tm => 'NYN', :cost =>383, :selected =>false}])
Pitcher.create([{ :name => 'Jered Weaver', :pos => 'SP', :tm => 'ANA', :cost =>376, :selected =>false}])
Pitcher.create([{ :name => 'Stephen Strasburg', :pos => 'SP', :tm => 'WAS', :cost =>369, :selected =>false}])
Pitcher.create([{ :name => 'Justin Verlander', :pos => 'SP', :tm => 'DET', :cost =>340, :selected =>false}])
Pitcher.create([{ :name => 'Roy Oswalt', :pos => 'SP', :tm => 'PHI', :cost =>336, :selected =>false}])
Pitcher.create([{ :name => 'Cole Hamels', :pos => 'SP', :tm => 'PHI', :cost =>333, :selected =>false}])
Pitcher.create([{ :name => 'Ted Lilly', :pos => 'SP', :tm => 'LAN', :cost =>332, :selected =>false}])
Pitcher.create([{ :name => 'Adam Wainwright', :pos => 'SP', :tm => 'SLN', :cost =>324, :selected =>false}])
Pitcher.create([{ :name => 'Matt Cain', :pos => 'SP', :tm => 'SFN', :cost =>322, :selected =>false}])
Pitcher.create([{ :name => 'Jake Peavy', :pos => 'SP', :tm => 'CHA', :cost =>318, :selected =>false}])
Pitcher.create([{ :name => 'Zack Greinke', :pos => 'SP', :tm => 'MIL', :cost =>299, :selected =>false}])
Pitcher.create([{ :name => 'Javier Vazquez', :pos => 'SP', :tm => 'FLO', :cost =>286, :selected =>false}])
Pitcher.create([{ :name => 'Jon Lester', :pos => 'SP', :tm => 'BOS', :cost =>278, :selected =>false}])
Pitcher.create([{ :name => 'Joe Nathan', :pos => 'SP', :tm => 'MIN', :cost =>275, :selected =>false}])
Pitcher.create([{ :name => 'Tommy Hanson', :pos => 'SP', :tm => 'ATL', :cost =>272, :selected =>false}])
Pitcher.create([{ :name => 'Chris Carpenter', :pos => 'SP', :tm => 'SLN', :cost =>271, :selected =>false}])
Pitcher.create([{ :name => 'David Price', :pos => 'SP', :tm => 'TBA', :cost =>268, :selected =>false}])
Pitcher.create([{ :name => 'Erik Bedard', :pos => 'SP', :tm => 'SEA', :cost =>265, :selected =>false}])
Pitcher.create([{ :name => 'Josh Johnson', :pos => 'SP', :tm => 'FLO', :cost =>263, :selected =>false}])
Pitcher.create([{ :name => 'Hiroki Kuroda', :pos => 'SP', :tm => 'LAN', :cost =>260, :selected =>false}])
Pitcher.create([{ :name => 'Mat Latos', :pos => 'SP', :tm => 'SDN', :cost =>257, :selected =>false}])
Pitcher.create([{ :name => 'James Shields', :pos => 'SP', :tm => 'TBA', :cost =>251, :selected =>false}])
Pitcher.create([{ :name => 'Winston Abreu', :pos => 'SP', :tm => 'TOR', :cost =>250, :selected =>false}])
Pitcher.create([{ :name => 'Mariano Rivera', :pos => 'SP', :tm => 'NYA', :cost =>249, :selected =>false}])
Pitcher.create([{ :name => 'Heath Bell', :pos => 'SP', :tm => 'SDN', :cost =>249, :selected =>false}])
Pitcher.create([{ :name => 'Josh Beckett', :pos => 'SP', :tm => 'BOS', :cost =>246, :selected =>false}])
Pitcher.create([{ :name => 'Clayton Kershaw', :pos => 'SP', :tm => 'LAN', :cost =>246, :selected =>false}])
Pitcher.create([{ :name => 'Jonathan Broxton', :pos => 'SP', :tm => 'LAN', :cost =>245, :selected =>false}])
Pitcher.create([{ :name => 'Max Scherzer', :pos => 'SP', :tm => 'DET', :cost =>241, :selected =>false}])
Pitcher.create([{ :name => 'Hong-Chih Kuo', :pos => 'SP', :tm => 'LAN', :cost =>240, :selected =>false}])
Pitcher.create([{ :name => 'Chad Billingsley', :pos => 'SP', :tm => 'LAN', :cost =>240, :selected =>false}])
Pitcher.create([{ :name => 'Brandon Webb', :pos => 'SP', :tm => 'TEX', :cost =>240, :selected =>false}])
Pitcher.create([{ :name => 'Colby Lewis', :pos => 'SP', :tm => 'TEX', :cost =>236, :selected =>false}])
Pitcher.create([{ :name => 'Jeremy Hellickson', :pos => 'SP', :tm => 'TBA', :cost =>235, :selected =>false}])
Pitcher.create([{ :name => 'Carlos Marmol', :pos => 'SP', :tm => 'CHN', :cost =>234, :selected =>false}])
Pitcher.create([{ :name => 'Ervin Santana', :pos => 'SP', :tm => 'ANA', :cost =>231, :selected =>false}])
Pitcher.create([{ :name => 'Sergio Romo', :pos => 'SP', :tm => 'SFN', :cost =>230, :selected =>false}])
Pitcher.create([{ :name => 'Wandy Rodriguez', :pos => 'SP', :tm => 'HOU', :cost =>230, :selected =>false}])
Pitcher.create([{ :name => 'Scott Baker', :pos => 'SP', :tm => 'MIN', :cost =>229, :selected =>false}])
Pitcher.create([{ :name => 'Jonathan Papelbon', :pos => 'SP', :tm => 'BOS', :cost =>227, :selected =>false}])
Pitcher.create([{ :name => 'Joaquin Benoit', :pos => 'SP', :tm => 'DET', :cost =>226, :selected =>false}])
Pitcher.create([{ :name => 'Mike Adams', :pos => 'SP', :tm => 'SDN', :cost =>226, :selected =>false}])
Pitcher.create([{ :name => 'Luke Gregerson', :pos => 'SP', :tm => 'SDN', :cost =>224, :selected =>false}])
Pitcher.create([{ :name => 'Matt Thornton', :pos => 'SP', :tm => 'CHA', :cost =>224, :selected =>false}])
Pitcher.create([{ :name => 'Dan Hudson', :pos => 'SP', :tm => 'ARI', :cost =>224, :selected =>false}])
Pitcher.create([{ :name => 'Ben Sheets', :pos => 'SP', :tm => 'OAK', :cost =>222, :selected =>false}])
Pitcher.create([{ :name => 'J.P. Howell', :pos => 'SP', :tm => 'TBA', :cost =>221, :selected =>false}])
Pitcher.create([{ :name => 'Clay Buchholz', :pos => 'SP', :tm => 'BOS', :cost =>221, :selected =>false}])
Pitcher.create([{ :name => 'Rafael Soriano', :pos => 'SP', :tm => 'NYA', :cost =>220, :selected =>false}])
Pitcher.create([{ :name => 'Francisco Liriano', :pos => 'SP', :tm => 'MIN', :cost =>220, :selected =>false}])
Pitcher.create([{ :name => 'Aroldis Chapman', :pos => 'SP', :tm => 'CIN', :cost =>219, :selected =>false}])
Pitcher.create([{ :name => 'Yovani Gallardo', :pos => 'SP', :tm => 'MIL', :cost =>219, :selected =>false}])
Pitcher.create([{ :name => 'Shaun Marcum', :pos => 'SP', :tm => 'MIL', :cost =>218, :selected =>false}])
Pitcher.create([{ :name => 'Joakim Soria', :pos => 'SP', :tm => 'KCA', :cost =>218, :selected =>false}])
Pitcher.create([{ :name => 'Ricky Nolasco', :pos => 'SP', :tm => 'FLO', :cost =>218, :selected =>false}])
Pitcher.create([{ :name => 'Brett Anderson', :pos => 'SP', :tm => 'OAK', :cost =>217, :selected =>false}])
Pitcher.create([{ :name => 'Phil Hughes', :pos => 'SP', :tm => 'NYA', :cost =>214, :selected =>false}])
Pitcher.create([{ :name => 'Chris Young', :pos => 'SP', :tm => 'NYN', :cost =>213, :selected =>false}])
Pitcher.create([{ :name => 'Dallas Braden', :pos => 'SP', :tm => 'OAK', :cost =>211, :selected =>false}])
Pitcher.create([{ :name => 'Tim Hudson', :pos => 'SP', :tm => 'ATL', :cost =>210, :selected =>false}])
Pitcher.create([{ :name => 'Takashi Saito', :pos => 'SP', :tm => 'ATL', :cost =>208, :selected =>false}])
Pitcher.create([{ :name => 'Joel Pineiro', :pos => 'SP', :tm => 'ANA', :cost =>208, :selected =>false}])
Pitcher.create([{ :name => 'Hisanori Takahashi', :pos => 'SP', :tm => 'ANA', :cost =>206, :selected =>false}])
Pitcher.create([{ :name => 'Rafael Betancourt', :pos => 'SP', :tm => 'COL', :cost =>205, :selected =>false}])
Pitcher.create([{ :name => 'Grant Balfour', :pos => 'SP', :tm => 'TBA', :cost =>200, :selected =>false}])
Pitcher.create([{ :name => 'Brett Myers', :pos => 'SP', :tm => 'HOU', :cost =>200, :selected =>false}])
Pitcher.create([{ :name => 'John Danks', :pos => 'SP', :tm => 'CHA', :cost =>200, :selected =>false}])
Pitcher.create([{ :name => 'Francisco Rodriguez', :pos => 'SP', :tm => 'NYN', :cost =>200, :selected =>false}])
Pitcher.create([{ :name => 'Kevin Slowey', :pos => 'SP', :tm => 'MIN', :cost =>200, :selected =>false}])
Pitcher.create([{ :name => 'Scott Downs', :pos => 'SP', :tm => 'ANA', :cost =>199, :selected =>false}])
Pitcher.create([{ :name => 'Joel Peralta', :pos => 'SP', :tm => 'TBA', :cost =>198, :selected =>false}])
Pitcher.create([{ :name => 'Jonathan Sanchez', :pos => 'SP', :tm => 'SFN', :cost =>197, :selected =>false}])
Pitcher.create([{ :name => 'Rich Harden', :pos => 'SP', :tm => 'OAK', :cost =>196, :selected =>false}])
Pitcher.create([{ :name => 'Brian Wilson', :pos => 'SP', :tm => 'SFN', :cost =>196, :selected =>false}])
Pitcher.create([{ :name => 'Madison Bumgarner', :pos => 'SP', :tm => 'SFN', :cost =>193, :selected =>false}])
Pitcher.create([{ :name => 'Trevor Cahill', :pos => 'SP', :tm => 'OAK', :cost =>193, :selected =>false}])
Pitcher.create([{ :name => 'Ryan Madson', :pos => 'SP', :tm => 'PHI', :cost =>192, :selected =>false}])
Pitcher.create([{ :name => 'Austin Hyatt', :pos => 'SP', :tm => 'PHI', :cost =>191, :selected =>false}])
Pitcher.create([{ :name => 'Dan Wheeler', :pos => 'SP', :tm => 'BOS', :cost =>191, :selected =>false}])
Pitcher.create([{ :name => 'Huston Street', :pos => 'SP', :tm => 'COL', :cost =>191, :selected =>false}])
Pitcher.create([{ :name => 'Craig Breslow', :pos => 'SP', :tm => 'OAK', :cost =>190, :selected =>false}])
Pitcher.create([{ :name => 'Craig Kimbrel', :pos => 'SP', :tm => 'ATL', :cost =>190, :selected =>false}])
Pitcher.create([{ :name => 'Andrew Bailey', :pos => 'SP', :tm => 'OAK', :cost =>188, :selected =>false}])
Pitcher.create([{ :name => 'Jose Valverde', :pos => 'SP', :tm => 'DET', :cost =>187, :selected =>false}])
Pitcher.create([{ :name => 'J.J. Putz', :pos => 'SP', :tm => 'ARI', :cost =>187, :selected =>false}])
Pitcher.create([{ :name => 'Jeff Niemann', :pos => 'SP', :tm => 'TBA', :cost =>187, :selected =>false}])
Pitcher.create([{ :name => 'David Robertson', :pos => 'SP', :tm => 'NYA', :cost =>186, :selected =>false}])
Pitcher.create([{ :name => 'Matt Garza', :pos => 'SP', :tm => 'CHN', :cost =>186, :selected =>false}])
Pitcher.create([{ :name => 'John Lackey', :pos => 'SP', :tm => 'BOS', :cost =>185, :selected =>false}])
Pitcher.create([{ :name => 'Darren Oliver', :pos => 'SP', :tm => 'TEX', :cost =>184, :selected =>false}])
Pitcher.create([{ :name => 'Michael Pineda', :pos => 'SP', :tm => 'SEA', :cost =>183, :selected =>false}])
Pitcher.create([{ :name => 'David Aardsma', :pos => 'SP', :tm => 'SEA', :cost =>181, :selected =>false}])
Pitcher.create([{ :name => 'Brian Matusz', :pos => 'SP', :tm => 'BAL', :cost =>181, :selected =>false}])
Pitcher.create([{ :name => 'Brandon League', :pos => 'SP', :tm => 'SEA', :cost =>180, :selected =>false}])
Pitcher.create([{ :name => 'Neftali Feliz', :pos => 'SP', :tm => 'TEX', :cost =>180, :selected =>false}])
Pitcher.create([{ :name => 'Gio Gonzalez', :pos => 'SP', :tm => 'OAK', :cost =>179, :selected =>false}])
Pitcher.create([{ :name => 'Koji Uehara', :pos => 'SP', :tm => 'BAL', :cost =>179, :selected =>false}])
Pitcher.create([{ :name => 'Bobby Jenks', :pos => 'SP', :tm => 'BOS', :cost =>178, :selected =>false}])
Pitcher.create([{ :name => 'Frank Francisco', :pos => 'SP', :tm => 'TEX', :cost =>176, :selected =>false}])
Pitcher.create([{ :name => 'Mike Minor', :pos => 'SP', :tm => 'ATL', :cost =>176, :selected =>false}])
Pitcher.create([{ :name => 'Jerry Blevins', :pos => 'SP', :tm => 'OAK', :cost =>175, :selected =>false}])
Pitcher.create([{ :name => 'Brian Fuentes', :pos => 'SP', :tm => 'MIN', :cost =>174, :selected =>false}])
Pitcher.create([{ :name => 'Ian Kennedy', :pos => 'SP', :tm => 'ARI', :cost =>174, :selected =>false}])
Pitcher.create([{ :name => 'Chris Perez', :pos => 'SP', :tm => 'CLE', :cost =>173, :selected =>false}])
Pitcher.create([{ :name => 'Jason Vargas', :pos => 'SP', :tm => 'SEA', :cost =>173, :selected =>false}])
Pitcher.create([{ :name => 'Ubaldo Jimenez', :pos => 'SP', :tm => 'COL', :cost =>172, :selected =>false}])
Pitcher.create([{ :name => 'Edward Mujica', :pos => 'SP', :tm => 'FLO', :cost =>170, :selected =>false}])
Pitcher.create([{ :name => 'Joba Chamberlain', :pos => 'SP', :tm => 'NYA', :cost =>169, :selected =>false}])
Pitcher.create([{ :name => 'Ryan Dempster', :pos => 'SP', :tm => 'CHN', :cost =>168, :selected =>false}])
Pitcher.create([{ :name => 'Gavin Floyd', :pos => 'SP', :tm => 'CHA', :cost =>168, :selected =>false}])
Pitcher.create([{ :name => 'Alexi Ogando', :pos => 'SP', :tm => 'TEX', :cost =>168, :selected =>false}])
Pitcher.create([{ :name => 'Matt Maloney', :pos => 'SP', :tm => 'CIN', :cost =>168, :selected =>false}])
Pitcher.create([{ :name => 'Edinson Volquez', :pos => 'SP', :tm => 'CIN', :cost =>168, :selected =>false}])
Pitcher.create([{ :name => 'Tyler Clippard', :pos => 'SP', :tm => 'WAS', :cost =>166, :selected =>false}])
Pitcher.create([{ :name => 'Justin Duchscherer', :pos => 'SP', :tm => 'OAK', :cost =>165, :selected =>false}])
Pitcher.create([{ :name => 'Drew Storen', :pos => 'SP', :tm => 'WAS', :cost =>164, :selected =>false}])
Pitcher.create([{ :name => 'Jason Frasor', :pos => 'SP', :tm => 'TOR', :cost =>163, :selected =>false}])
Pitcher.create([{ :name => 'Christopher Sale', :pos => 'SP', :tm => 'CHA', :cost =>163, :selected =>false}])
Pitcher.create([{ :name => 'Scott Kazmir', :pos => 'SP', :tm => 'ANA', :cost =>163, :selected =>false}])
Pitcher.create([{ :name => 'Dustin McGowan', :pos => 'SP', :tm => 'TOR', :cost =>162, :selected =>false}])
Pitcher.create([{ :name => 'Brandon Beachey', :pos => 'SP', :tm => 'ATL', :cost =>162, :selected =>false}])
Pitcher.create([{ :name => 'Chad Qualls', :pos => 'SP', :tm => 'SDN', :cost =>161, :selected =>false}])
Pitcher.create([{ :name => 'C.J. Wilson', :pos => 'SP', :tm => 'TEX', :cost =>161, :selected =>false}])
Pitcher.create([{ :name => 'Jon Rauch', :pos => 'SP', :tm => 'MIN', :cost =>160, :selected =>false}])
Pitcher.create([{ :name => 'Jeremy Guthrie', :pos => 'SP', :tm => 'BAL', :cost =>159, :selected =>false}])
Pitcher.create([{ :name => 'Scott Mathieson', :pos => 'SP', :tm => 'PHI', :cost =>156, :selected =>false}])
Pitcher.create([{ :name => 'Jason Motte', :pos => 'SP', :tm => 'SLN', :cost =>156, :selected =>false}])
Pitcher.create([{ :name => 'Carlos Villanueva', :pos => 'SP', :tm => 'TOR', :cost =>156, :selected =>false}])
Pitcher.create([{ :name => 'Aaron Harang', :pos => 'SP', :tm => 'SDN', :cost =>156, :selected =>false}])
Pitcher.create([{ :name => 'Bronson Arroyo', :pos => 'SP', :tm => 'CIN', :cost =>156, :selected =>false}])
Pitcher.create([{ :name => 'Nelson Figueroa', :pos => 'SP', :tm => 'HOU', :cost =>155, :selected =>false}])
Pitcher.create([{ :name => 'Daniel Bard', :pos => 'SP', :tm => 'BOS', :cost =>154, :selected =>false}])
Pitcher.create([{ :name => 'Mike Gonzalez', :pos => 'SP', :tm => 'BAL', :cost =>153, :selected =>false}])
Pitcher.create([{ :name => 'Kyle Farnsworth', :pos => 'SP', :tm => 'TBA', :cost =>153, :selected =>false}])
Pitcher.create([{ :name => 'Matt Capps', :pos => 'SP', :tm => 'MIN', :cost =>153, :selected =>false}])
Pitcher.create([{ :name => 'Brandon Lyon', :pos => 'SP', :tm => 'HOU', :cost =>152, :selected =>false}])
Pitcher.create([{ :name => 'Wade Davis', :pos => 'SP', :tm => 'TBA', :cost =>152, :selected =>false}])
Pitcher.create([{ :name => 'Wade LeBlanc', :pos => 'SP', :tm => 'SDN', :cost =>149, :selected =>false}])
Pitcher.create([{ :name => 'Brad Ziegler', :pos => 'SP', :tm => 'OAK', :cost =>148, :selected =>false}])
Pitcher.create([{ :name => 'Brandon Morrow', :pos => 'SP', :tm => 'TOR', :cost =>146, :selected =>false}])
Pitcher.create([{ :name => 'Octavio Dotel', :pos => 'SP', :tm => 'TOR', :cost =>146, :selected =>false}])
Pitcher.create([{ :name => 'Jaime Garcia', :pos => 'SP', :tm => 'SLN', :cost =>146, :selected =>false}])
Pitcher.create([{ :name => 'Travis Wood', :pos => 'SP', :tm => 'CIN', :cost =>146, :selected =>false}])
Pitcher.create([{ :name => 'Kyle McClellan', :pos => 'SP', :tm => 'SLN', :cost =>145, :selected =>false}])
Pitcher.create([{ :name => 'Johnny Cueto', :pos => 'SP', :tm => 'CIN', :cost =>144, :selected =>false}])
Pitcher.create([{ :name => 'Kevin Gregg', :pos => 'SP', :tm => 'BAL', :cost =>144, :selected =>false}])
Pitcher.create([{ :name => 'Arthur Rhodes', :pos => 'SP', :tm => 'TEX', :cost =>143, :selected =>false}])
Pitcher.create([{ :name => 'Francisco Cordero', :pos => 'SP', :tm => 'CIN', :cost =>143, :selected =>false}])
Pitcher.create([{ :name => 'Leo Nunez', :pos => 'SP', :tm => 'FLO', :cost =>143, :selected =>false}])
Pitcher.create([{ :name => 'Daisuke Matsuzaka', :pos => 'SP', :tm => 'BOS', :cost =>142, :selected =>false}])
Pitcher.create([{ :name => 'Jair Jurrjens', :pos => 'SP', :tm => 'ATL', :cost =>142, :selected =>false}])
Pitcher.create([{ :name => 'Jordan Zimmermann', :pos => 'SP', :tm => 'WAS', :cost =>142, :selected =>false}])
Pitcher.create([{ :name => 'Ryan Franklin', :pos => 'SP', :tm => 'SLN', :cost =>142, :selected =>false}])
Pitcher.create([{ :name => 'Sean Marshall', :pos => 'SP', :tm => 'CHN', :cost =>141, :selected =>false}])
Pitcher.create([{ :name => 'Brad Lidge', :pos => 'SP', :tm => 'PHI', :cost =>141, :selected =>false}])
Pitcher.create([{ :name => 'Dillon Gee', :pos => 'SP', :tm => 'NYN', :cost =>141, :selected =>false}])
Pitcher.create([{ :name => 'Derek Lowe', :pos => 'SP', :tm => 'ATL', :cost =>140, :selected =>false}])
Pitcher.create([{ :name => 'Jesse Crain', :pos => 'SP', :tm => 'CHA', :cost =>140, :selected =>false}])
Pitcher.create([{ :name => 'Brandon Mccarthy', :pos => 'SP', :tm => 'OAK', :cost =>140, :selected =>false}])
Pitcher.create([{ :name => 'Kerry Wood', :pos => 'SP', :tm => 'CHN', :cost =>140, :selected =>false}])
Pitcher.create([{ :name => 'Carl Pavano', :pos => 'SP', :tm => 'MIN', :cost =>139, :selected =>false}])
Pitcher.create([{ :name => 'Nick Masset', :pos => 'SP', :tm => 'CIN', :cost =>139, :selected =>false}])
Pitcher.create([{ :name => 'John Maine', :pos => 'SP', :tm => 'NYN', :cost =>136, :selected =>false}])
Pitcher.create([{ :name => 'Matt Moore', :pos => 'SP', :tm => 'TBA', :cost =>133, :selected =>false}])
Pitcher.create([{ :name => 'Rafael Perez', :pos => 'SP', :tm => 'CLE', :cost =>132, :selected =>false}])
Pitcher.create([{ :name => 'Jacob McGee', :pos => 'SP', :tm => 'TBA', :cost =>132, :selected =>false}])
Pitcher.create([{ :name => 'Joe Smith', :pos => 'SP', :tm => 'CLE', :cost =>132, :selected =>false}])
Pitcher.create([{ :name => 'Patrick Misch', :pos => 'SP', :tm => 'NYN', :cost =>131, :selected =>false}])
Pitcher.create([{ :name => 'Tim Stauffer', :pos => 'SP', :tm => 'SDN', :cost =>130, :selected =>false}])
Pitcher.create([{ :name => 'Vicente Padilla', :pos => 'SP', :tm => 'LAN', :cost =>130, :selected =>false}])
Pitcher.create([{ :name => 'Josh Tomlin', :pos => 'SP', :tm => 'CLE', :cost =>130, :selected =>false}])
Pitcher.create([{ :name => 'Chris Capuano', :pos => 'SP', :tm => 'NYN', :cost =>129, :selected =>false}])
Pitcher.create([{ :name => 'Scott Linebrink', :pos => 'SP', :tm => 'ATL', :cost =>128, :selected =>false}])
Pitcher.create([{ :name => 'Robinson Tejeda', :pos => 'SP', :tm => 'KCA', :cost =>128, :selected =>false}])
Pitcher.create([{ :name => 'Andy Sonnanstine', :pos => 'SP', :tm => 'TBA', :cost =>128, :selected =>false}])
Pitcher.create([{ :name => 'Santiago Casilla', :pos => 'SP', :tm => 'SFN', :cost =>127, :selected =>false}])
Pitcher.create([{ :name => 'Latroy Hawkins', :pos => 'SP', :tm => 'MIL', :cost =>126, :selected =>false}])
Pitcher.create([{ :name => 'Justin Masterson', :pos => 'SP', :tm => 'CLE', :cost =>126, :selected =>false}])
Pitcher.create([{ :name => 'Casey Janssen', :pos => 'SP', :tm => 'TOR', :cost =>124, :selected =>false}])
Pitcher.create([{ :name => 'George Sherrill', :pos => 'SP', :tm => 'ATL', :cost =>124, :selected =>false}])
Pitcher.create([{ :name => 'Kyle Gibson', :pos => 'SP', :tm => 'MIN', :cost =>123, :selected =>false}])
Pitcher.create([{ :name => 'Randy Choate', :pos => 'SP', :tm => 'FLO', :cost =>123, :selected =>false}])
Pitcher.create([{ :name => 'Daniel Runzler', :pos => 'SP', :tm => 'SFN', :cost =>122, :selected =>false}])
Pitcher.create([{ :name => 'Joel Zumaya', :pos => 'SP', :tm => 'DET', :cost =>122, :selected =>false}])
Pitcher.create([{ :name => 'Brett Cecil', :pos => 'SP', :tm => 'TOR', :cost =>122, :selected =>false}])
Pitcher.create([{ :name => 'Randy Wolf', :pos => 'SP', :tm => 'MIL', :cost =>122, :selected =>false}])
Pitcher.create([{ :name => 'James McDonald', :pos => 'SP', :tm => 'PIT', :cost =>122, :selected =>false}])
Pitcher.create([{ :name => 'Fernando Rodney', :pos => 'SP', :tm => 'ANA', :cost =>121, :selected =>false}])
Pitcher.create([{ :name => 'Joel Hanrahan', :pos => 'SP', :tm => 'PIT', :cost =>121, :selected =>false}])
Pitcher.create([{ :name => 'J.A. Happ', :pos => 'SP', :tm => 'HOU', :cost =>120, :selected =>false}])
Pitcher.create([{ :name => 'Joe Blanton', :pos => 'SP', :tm => 'PHI', :cost =>120, :selected =>false}])
Pitcher.create([{ :name => 'Todd Coffey', :pos => 'SP', :tm => 'MIL', :cost =>120, :selected =>false}])
Pitcher.create([{ :name => 'A.J. Burnett', :pos => 'SP', :tm => 'NYA', :cost =>120, :selected =>false}])
Pitcher.create([{ :name => 'Jose Contreras', :pos => 'SP', :tm => 'PHI', :cost =>120, :selected =>false}])
Pitcher.create([{ :name => 'Douglas Fister', :pos => 'RP', :tm => 'SEA', :cost =>119, :selected =>false}])
Pitcher.create([{ :name => 'Andy Pettitte', :pos => 'RP', :tm => 'NYA', :cost =>118, :selected =>false}])
Pitcher.create([{ :name => 'Garrett Olson', :pos => 'RP', :tm => 'SEA', :cost =>118, :selected =>false}])
Pitcher.create([{ :name => 'Boone Logan', :pos => 'RP', :tm => 'NYA', :cost =>118, :selected =>false}])
Pitcher.create([{ :name => 'Evan Meek', :pos => 'RP', :tm => 'PIT', :cost =>117, :selected =>false}])
Pitcher.create([{ :name => 'Anibal Sanchez', :pos => 'RP', :tm => 'FLO', :cost =>116, :selected =>false}])
Pitcher.create([{ :name => 'Omar Beltre', :pos => 'RP', :tm => 'TEX', :cost =>116, :selected =>false}])
Pitcher.create([{ :name => 'Phil Coke', :pos => 'RP', :tm => 'DET', :cost =>115, :selected =>false}])
Pitcher.create([{ :name => 'David Pauley', :pos => 'RP', :tm => 'SEA', :cost =>114, :selected =>false}])
Pitcher.create([{ :name => 'Jake Westbrook', :pos => 'RP', :tm => 'SLN', :cost =>113, :selected =>false}])
Pitcher.create([{ :name => 'Will Ohman', :pos => 'RP', :tm => 'CHA', :cost =>113, :selected =>false}])
Pitcher.create([{ :name => 'Lance Lynn', :pos => 'RP', :tm => 'SLN', :cost =>113, :selected =>false}])
Pitcher.create([{ :name => 'Chad Durbin', :pos => 'RP', :tm => 'PHI', :cost =>112, :selected =>false}])
Pitcher.create([{ :name => 'Barry Zito', :pos => 'RP', :tm => 'SFN', :cost =>112, :selected =>false}])
Pitcher.create([{ :name => 'R.A. Dickey', :pos => 'RP', :tm => 'NYN', :cost =>110, :selected =>false}])
Pitcher.create([{ :name => 'Sergio Santos', :pos => 'RP', :tm => 'CHA', :cost =>109, :selected =>false}])
Pitcher.create([{ :name => 'Raul Valdez', :pos => 'RP', :tm => 'SLN', :cost =>109, :selected =>false}])
Pitcher.create([{ :name => 'Clayton Richard', :pos => 'RP', :tm => 'SDN', :cost =>109, :selected =>false}])
Pitcher.create([{ :name => 'Carlos Zambrano', :pos => 'RP', :tm => 'CHN', :cost =>109, :selected =>false}])
Pitcher.create([{ :name => 'Michael Bowden', :pos => 'RP', :tm => 'BOS', :cost =>108, :selected =>false}])
Pitcher.create([{ :name => 'Derek Holland', :pos => 'RP', :tm => 'TEX', :cost =>108, :selected =>false}])
Pitcher.create([{ :name => 'Bruce Chen', :pos => 'RP', :tm => 'KCA', :cost =>107, :selected =>false}])
Pitcher.create([{ :name => 'Aaron Heilman', :pos => 'RP', :tm => 'ARI', :cost =>107, :selected =>false}])
Pitcher.create([{ :name => 'Sean Burnett', :pos => 'RP', :tm => 'WAS', :cost =>106, :selected =>false}])
Pitcher.create([{ :name => 'Kevin Jepsen', :pos => 'RP', :tm => 'ANA', :cost =>106, :selected =>false}])
Pitcher.create([{ :name => 'Joseph Gardner', :pos => 'RP', :tm => 'CLE', :cost =>106, :selected =>false}])
Pitcher.create([{ :name => 'Fausto Carmona', :pos => 'RP', :tm => 'CLE', :cost =>104, :selected =>false}])
Pitcher.create([{ :name => 'Jesse Litsch', :pos => 'RP', :tm => 'TOR', :cost =>100, :selected =>false}])
Pitcher.create([{ :name => 'Rick Porcello', :pos => 'RP', :tm => 'DET', :cost =>99, :selected =>false}])
Pitcher.create([{ :name => 'Mark Buehrle', :pos => 'RP', :tm => 'CHA', :cost =>99, :selected =>false}])
Pitcher.create([{ :name => 'Jake Arrieta', :pos => 'RP', :tm => 'BAL', :cost =>99, :selected =>false}])
Pitcher.create([{ :name => 'Matt Belisle', :pos => 'RP', :tm => 'COL', :cost =>97, :selected =>false}])
Pitcher.create([{ :name => 'Chien-Ming Wang', :pos => 'RP', :tm => 'WAS', :cost =>96, :selected =>false}])
Pitcher.create([{ :name => 'Jon Garland', :pos => 'RP', :tm => 'LAN', :cost =>96, :selected =>false}])
Pitcher.create([{ :name => 'Bradley Boxberger', :pos => 'RP', :tm => 'CIN', :cost =>95, :selected =>false}])
Pitcher.create([{ :name => 'Brad Penny', :pos => 'RP', :tm => 'DET', :cost =>95, :selected =>false}])
Pitcher.create([{ :name => 'P.J. Walters', :pos => 'RP', :tm => 'SLN', :cost =>95, :selected =>false}])
Pitcher.create([{ :name => 'Chris Narveson', :pos => 'RP', :tm => 'MIL', :cost =>94, :selected =>false}])
Pitcher.create([{ :name => 'Kevin Correia', :pos => 'RP', :tm => 'PIT', :cost =>94, :selected =>false}])
Pitcher.create([{ :name => 'Rich Hill', :pos => 'RP', :tm => 'BOS', :cost =>94, :selected =>false}])
Pitcher.create([{ :name => 'D.J. Carrasco', :pos => 'RP', :tm => 'NYN', :cost =>92, :selected =>false}])
Pitcher.create([{ :name => 'Brian Duensing', :pos => 'RP', :tm => 'MIN', :cost =>92, :selected =>false}])
Pitcher.create([{ :name => 'Carlos Torres', :pos => 'RP', :tm => 'CHA', :cost =>92, :selected =>false}])
Pitcher.create([{ :name => 'Bud Norris', :pos => 'RP', :tm => 'HOU', :cost =>92, :selected =>false}])
Pitcher.create([{ :name => 'Chad Gaudin', :pos => 'RP', :tm => 'WAS', :cost =>91, :selected =>false}])
Pitcher.create([{ :name => 'Alex White', :pos => 'RP', :tm => 'CLE', :cost =>90, :selected =>false}])
Pitcher.create([{ :name => 'Carlos Carrasco', :pos => 'RP', :tm => 'CLE', :cost =>88, :selected =>false}])
Pitcher.create([{ :name => 'Junichi Tazawa', :pos => 'RP', :tm => 'BOS', :cost =>88, :selected =>false}])
Pitcher.create([{ :name => 'Ryan Rowland-Smith', :pos => 'RP', :tm => 'HOU', :cost =>85, :selected =>false}])
Pitcher.create([{ :name => 'Jeff Francis', :pos => 'RP', :tm => 'KCA', :cost =>84, :selected =>false}])
Pitcher.create([{ :name => 'John Axford', :pos => 'RP', :tm => 'MIL', :cost =>84, :selected =>false}])
Pitcher.create([{ :name => 'Armando Galarraga', :pos => 'RP', :tm => 'DET', :cost =>81, :selected =>false}])
Pitcher.create([{ :name => 'Luke Hochevar', :pos => 'RP', :tm => 'KCA', :cost =>81, :selected =>false}])
Pitcher.create([{ :name => 'Gil Meche', :pos => 'RP', :tm => 'KCA', :cost =>80, :selected =>false}])
Pitcher.create([{ :name => 'Andrew Cashner', :pos => 'RP', :tm => 'CHN', :cost =>79, :selected =>false}])
Pitcher.create([{ :name => 'Edwin Jackson', :pos => 'RP', :tm => 'CHA', :cost =>79, :selected =>false}])
Pitcher.create([{ :name => 'Jeff Fulchino', :pos => 'RP', :tm => 'HOU', :cost =>78, :selected =>false}])
Pitcher.create([{ :name => 'Wilton Lopez', :pos => 'RP', :tm => 'HOU', :cost =>77, :selected =>false}])
Pitcher.create([{ :name => 'Kenshin Kawakami', :pos => 'RP', :tm => 'ATL', :cost =>77, :selected =>false}])
Pitcher.create([{ :name => 'Chris Tillman', :pos => 'RP', :tm => 'BAL', :cost =>77, :selected =>false}])
Pitcher.create([{ :name => 'Mike Pelfrey', :pos => 'RP', :tm => 'NYN', :cost =>77, :selected =>false}])
Pitcher.create([{ :name => 'Homer Bailey', :pos => 'RP', :tm => 'CIN', :cost =>76, :selected =>false}])
Pitcher.create([{ :name => 'Matt Lindstrom', :pos => 'RP', :tm => 'COL', :cost =>76, :selected =>false}])
Pitcher.create([{ :name => 'Radhames Liz', :pos => 'RP', :tm => 'SDN', :cost =>74, :selected =>false}])
Pitcher.create([{ :name => 'Randy Wells', :pos => 'RP', :tm => 'CHN', :cost =>74, :selected =>false}])
Pitcher.create([{ :name => 'Scott Richmond', :pos => 'RP', :tm => 'TOR', :cost =>73, :selected =>false}])
Pitcher.create([{ :name => 'Scott Richmond', :pos => 'RP', :tm => 'TOR', :cost =>73, :selected =>false}])
Pitcher.create([{ :name => 'Andrew Oliver', :pos => 'RP', :tm => 'DET', :cost =>73, :selected =>false}])
Pitcher.create([{ :name => 'David Huff', :pos => 'RP', :tm => 'CLE', :cost =>72, :selected =>false}])
Pitcher.create([{ :name => 'Josh Outman', :pos => 'RP', :tm => 'OAK', :cost =>72, :selected =>false}])
Pitcher.create([{ :name => 'Daniel McCutchen', :pos => 'RP', :tm => 'PIT', :cost =>71, :selected =>false}])
Pitcher.create([{ :name => 'Jeremy Bonderman', :pos => 'RP', :tm => 'DET', :cost =>71, :selected =>false}])
Pitcher.create([{ :name => 'Kyle Drabek', :pos => 'RP', :tm => 'TOR', :cost =>71, :selected =>false}])
Pitcher.create([{ :name => 'Brad Lincoln', :pos => 'RP', :tm => 'PIT', :cost =>70, :selected =>false}])
Pitcher.create([{ :name => 'Henry Alberto Rodriguez', :pos => 'RP', :tm => 'WAS', :cost =>68, :selected =>false}])
Pitcher.create([{ :name => 'Nick Blackburn', :pos => 'RP', :tm => 'MIN', :cost =>67, :selected =>false}])
Pitcher.create([{ :name => 'Clay Hensley', :pos => 'RP', :tm => 'FLO', :cost =>67, :selected =>false}])
Pitcher.create([{ :name => 'Jonathon Niese', :pos => 'RP', :tm => 'NYN', :cost =>67, :selected =>false}])
Pitcher.create([{ :name => 'Charles Furbush', :pos => 'RP', :tm => 'DET', :cost =>67, :selected =>false}])
Pitcher.create([{ :name => 'Fernando Nieve', :pos => 'RP', :tm => 'PIT', :cost =>65, :selected =>false}])
Pitcher.create([{ :name => 'Jonathan Venters', :pos => 'RP', :tm => 'ATL', :cost =>65, :selected =>false}])
Pitcher.create([{ :name => 'Ross Ohlendorf', :pos => 'RP', :tm => 'PIT', :cost =>65, :selected =>false}])
Pitcher.create([{ :name => 'David Purcey', :pos => 'RP', :tm => 'TOR', :cost =>63, :selected =>false}])
Pitcher.create([{ :name => 'Mitch Talbot', :pos => 'RP', :tm => 'CLE', :cost =>63, :selected =>false}])
Pitcher.create([{ :name => 'Lance Pendleton', :pos => 'RP', :tm => 'HOU', :cost =>62, :selected =>false}])
Pitcher.create([{ :name => 'Ricky Romero', :pos => 'RP', :tm => 'TOR', :cost =>62, :selected =>false}])
Pitcher.create([{ :name => 'Sam Lecure', :pos => 'RP', :tm => 'CIN', :cost =>61, :selected =>false}])
Pitcher.create([{ :name => 'Marc Rzepczynski', :pos => 'RP', :tm => 'TOR', :cost =>60, :selected =>false}])
Pitcher.create([{ :name => 'Tom Gorzelanny', :pos => 'RP', :tm => 'CHN', :cost =>59, :selected =>false}])
Pitcher.create([{ :name => 'Tom Gorzelanny', :pos => 'RP', :tm => 'WAS', :cost =>59, :selected =>false}])
Pitcher.create([{ :name => 'Mike Leake', :pos => 'RP', :tm => 'CIN', :cost =>59, :selected =>false}])
Pitcher.create([{ :name => 'Jordan Lyles', :pos => 'RP', :tm => 'HOU', :cost =>57, :selected =>false}])
Pitcher.create([{ :name => 'Adalberto Mendez', :pos => 'RP', :tm => 'FLO', :cost =>57, :selected =>false}])
Pitcher.create([{ :name => 'Kameron Loe', :pos => 'RP', :tm => 'MIL', :cost =>56, :selected =>false}])
Pitcher.create([{ :name => 'Todd Redmond', :pos => 'RP', :tm => 'ATL', :cost =>55, :selected =>false}])
Pitcher.create([{ :name => 'Jhoulys Chacin', :pos => 'RP', :tm => 'COL', :cost =>55, :selected =>false}])
Pitcher.create([{ :name => 'Micah Owings', :pos => 'RP', :tm => 'CIN', :cost =>53, :selected =>false}])
Pitcher.create([{ :name => 'Kyle Lohse', :pos => 'RP', :tm => 'SLN', :cost =>53, :selected =>false}])
Pitcher.create([{ :name => 'Clayton Mortensen', :pos => 'RP', :tm => 'OAK', :cost =>49, :selected =>false}])
Pitcher.create([{ :name => 'Tim Wakefield', :pos => 'RP', :tm => 'BOS', :cost =>48, :selected =>false}])
Pitcher.create([{ :name => 'Tommy Hunter', :pos => 'RP', :tm => 'TEX', :cost =>48, :selected =>false}])
Pitcher.create([{ :name => 'David Hernandez', :pos => 'RP', :tm => 'ARI', :cost =>46, :selected =>false}])
Pitcher.create([{ :name => 'Brad Bergesen', :pos => 'RP', :tm => 'BAL', :cost =>46, :selected =>false}])
Pitcher.create([{ :name => 'Brian Bannister', :pos => 'RP', :tm => 'KCA', :cost =>45, :selected =>false}])
Pitcher.create([{ :name => 'Ian Snell', :pos => 'RP', :tm => 'SEA', :cost =>45, :selected =>false}])
Pitcher.create([{ :name => 'Charlie Morton', :pos => 'RP', :tm => 'PIT', :cost =>45, :selected =>false}])
Pitcher.create([{ :name => 'Blake Wood', :pos => 'RP', :tm => 'KCA', :cost =>44, :selected =>false}])
Pitcher.create([{ :name => 'Jorge de la Rosa', :pos => 'RP', :tm => 'COL', :cost =>43, :selected =>false}])
Pitcher.create([{ :name => 'Bobby Parnell', :pos => 'RP', :tm => 'NYN', :cost =>41, :selected =>false}])
Pitcher.create([{ :name => 'Charlie Haeger', :pos => 'RP', :tm => 'SEA', :cost =>39, :selected =>false}])
Pitcher.create([{ :name => 'Kyle Davies', :pos => 'RP', :tm => 'KCA', :cost =>37, :selected =>false}])
Pitcher.create([{ :name => 'John Ely', :pos => 'RP', :tm => 'LAN', :cost =>36, :selected =>false}])
Pitcher.create([{ :name => 'Lucas French', :pos => 'RP', :tm => 'SEA', :cost =>36, :selected =>false}])
Pitcher.create([{ :name => 'Dave Bush', :pos => 'RP', :tm => 'TEX', :cost =>36, :selected =>false}])
Pitcher.create([{ :name => 'Scott Feldman', :pos => 'RP', :tm => 'TEX', :cost =>35, :selected =>false}])
Pitcher.create([{ :name => 'Juan Gutierrez', :pos => 'RP', :tm => 'ARI', :cost =>34, :selected =>false}])
Pitcher.create([{ :name => 'Randall Delgado', :pos => 'RP', :tm => 'ATL', :cost =>33, :selected =>false}])
Pitcher.create([{ :name => 'Jason Marquis', :pos => 'RP', :tm => 'WAS', :cost =>30, :selected =>false}])
Pitcher.create([{ :name => 'Vin Mazzaro', :pos => 'RP', :tm => 'KCA', :cost =>29, :selected =>false}])
Pitcher.create([{ :name => 'Jason Hammel', :pos => 'RP', :tm => 'COL', :cost =>26, :selected =>false}])
Pitcher.create([{ :name => 'Joe Saunders', :pos => 'RP', :tm => 'ARI', :cost =>25, :selected =>false}])
Pitcher.create([{ :name => 'Justin Wilson', :pos => 'RP', :tm => 'PIT', :cost =>25, :selected =>false}])
Pitcher.create([{ :name => 'Amaury Rivas', :pos => 'RP', :tm => 'MIL', :cost =>24, :selected =>false}])
Pitcher.create([{ :name => 'John Lannan', :pos => 'RP', :tm => 'WAS', :cost =>24, :selected =>false}])
Pitcher.create([{ :name => 'Jim Russell', :pos => 'RP', :tm => 'CHN', :cost =>21, :selected =>false}])
Pitcher.create([{ :name => 'Eric Hurley', :pos => 'RP', :tm => 'TEX', :cost =>21, :selected =>false}])
Pitcher.create([{ :name => 'Paul Maholm', :pos => 'RP', :tm => 'PIT', :cost =>21, :selected =>false}])
Pitcher.create([{ :name => 'Kyle Kendrick', :pos => 'RP', :tm => 'PHI', :cost =>20, :selected =>false}])
Pitcher.create([{ :name => 'Dan Cortes', :pos => 'RP', :tm => 'SEA', :cost =>18, :selected =>false}])
Pitcher.create([{ :name => 'Kevin Millwood', :pos => 'RP', :tm => 'BAL', :cost =>18, :selected =>false}])
Pitcher.create([{ :name => 'Ross Detwiler', :pos => 'RP', :tm => 'WAS', :cost =>14, :selected =>false}])
Pitcher.create([{ :name => 'Sean West', :pos => 'RP', :tm => 'FLO', :cost =>14, :selected =>false}])
Pitcher.create([{ :name => 'Felipe Paulino', :pos => 'RP', :tm => 'COL', :cost =>13, :selected =>false}])
Pitcher.create([{ :name => 'Manny Parra', :pos => 'RP', :tm => 'MIL', :cost =>12, :selected =>false}])
Pitcher.create([{ :name => 'Samuel Deduno', :pos => 'RP', :tm => 'COL', :cost =>11, :selected =>false}])
Pitcher.create([{ :name => 'Aaron Laffey', :pos => 'RP', :tm => 'CLE', :cost =>10, :selected =>false}])
Pitcher.create([{ :name => 'Oliver Perez', :pos => 'RP', :tm => 'NYN', :cost =>9, :selected =>false}])
Pitcher.create([{ :name => 'Aneury Rodriguez', :pos => 'RP', :tm => 'HOU', :cost =>9, :selected =>false}])
Pitcher.create([{ :name => 'Esmerling Vasquez', :pos => 'RP', :tm => 'ARI', :cost =>8, :selected =>false}])
Pitcher.create([{ :name => 'Mitch Atkins', :pos => 'RP', :tm => 'BAL', :cost =>7, :selected =>false}])
Pitcher.create([{ :name => 'Carlos Silva', :pos => 'RP', :tm => 'CHN', :cost =>7, :selected =>false}])
Pitcher.create([{ :name => 'Barry Enright', :pos => 'RP', :tm => 'ARI', :cost =>6, :selected =>false}])
Pitcher.create([{ :name => 'Chris Volstad', :pos => 'RP', :tm => 'FLO', :cost =>3, :selected =>false}])
Pitcher.create([{ :name => 'Scott Olsen', :pos => 'RP', :tm => 'PIT', :cost =>1, :selected =>false}])
Pitcher.create([{ :name => 'Gregory Infante', :pos => 'RP', :tm => 'CHA', :cost =>1, :selected =>false}])
Pitcher.create([{ :name => 'Casey Coleman', :pos => 'RP', :tm => 'CHN', :cost =>1, :selected =>false}])
Pitcher.create([{ :name => 'Juan Nicasio', :pos => 'RP', :tm => 'COL', :cost =>1, :selected =>false}])
Pitcher.create([{ :name => 'Corey Kluber', :pos => 'RP', :tm => 'CLE', :cost =>1, :selected =>false}])
Pitcher.create([{ :name => 'Carlos Monasterios', :pos => 'RP', :tm => 'LAN', :cost =>1, :selected =>false}])
Pitcher.create([{ :name => 'Sean OSullivan', :pos => 'RP', :tm => 'KCA', :cost =>1, :selected =>false}])
Pitcher.create([{ :name => 'Rodrigo Lopez', :pos => 'RP', :tm => 'ARI', :cost =>1, :selected =>false}])
Pitcher.create([{ :name => 'D.J. Mitchell', :pos => 'RP', :tm => 'NYA', :cost =>1, :selected =>false}])
Pitcher.create([{ :name => 'Luis Atilano', :pos => 'RP', :tm => 'WAS', :cost =>1, :selected =>false}])
Pitcher.create([{ :name => 'Doug Davis', :pos => 'RP', :tm => 'MIL', :cost =>1, :selected =>false}])
Pitcher.create([{ :name => 'Jeanmar Gomez', :pos => 'RP', :tm => 'CLE', :cost =>1, :selected =>false}])
Pitcher.create([{ :name => 'Aaron Crow', :pos => 'RP', :tm => 'KCA', :cost =>1, :selected =>false}])
Pitcher.create([{ :name => 'Zach Duke', :pos => 'RP', :tm => 'PIT', :cost =>1, :selected =>false}])
Pitcher.create([{ :name => 'Aaron Cook', :pos => 'RP', :tm => 'COL', :cost =>1, :selected =>false}])
Pitcher.create([{ :name => 'Livan Hernandez', :pos => 'RP', :tm => 'WAS', :cost =>1, :selected =>false}])
Pitcher.create([{ :name => 'Pedro Beato', :pos => 'RP', :tm => 'NYN', :cost =>1, :selected =>false}])
Pitcher.create([{ :name => 'Esmil Rogers', :pos => 'RP', :tm => 'COL', :cost =>1, :selected =>false}])
Pitcher.create([{ :name => 'Eric Stults', :pos => 'RP', :tm => 'COL', :cost =>1, :selected =>false}])
Pitcher.create([{ :name => 'Jeff Suppan', :pos => 'RP', :tm => 'SLN', :cost =>1, :selected =>false}])
Team.create([{ :team_name => 'Snoop', :spent =>395, :num_players =>1, :image => 'snoop.png'}])
Team.create([{ :team_name => 'Bachs Cello Sweets', :spent =>399, :num_players =>1, :image => 'sweets.png'}])
Team.create([{ :team_name => 'Round Rock Expresso', :spent =>425, :num_players =>1, :image => 'rrx.png'}])
Team.create([{ :team_name => 'Kosky Reds', :spent =>464, :num_players =>1, :image => 'reds.png'}])
Team.create([{ :team_name => 'Jackson Bandits', :spent =>491, :num_players =>1, :image => 'bandits.png'}])
Team.create([{ :team_name => 'Go Mordecai', :spent =>352, :num_players =>1, :image => 'mordecai.png'}])
Team.create([{ :team_name => 'Big Moose', :spent =>274, :num_players =>1, :image => 'moose.png'}])
Team.create([{ :team_name => 'Les Hommes dEte', :spent =>387, :num_players =>1, :image => 'hommes.png'}])
Team.create([{ :team_name => 'Yes Yes Nannie', :spent =>346, :num_players =>1, :image => 'nannie.png'}])
Team.create([{ :team_name => 'Hypnotic Pretzels', :spent =>469, :num_players =>1, :image => 'pretzels.png'}])
Draft.create([{ :player_type => 'Pitcher', :player_num =>5, :team_id => 0}])
Draft.create([{ :player_type => 'Pitcher', :player_num =>4, :team_id => 1}])
Draft.create([{ :player_type => 'Pitcher', :player_num =>3, :team_id => 2}])
Draft.create([{ :player_type => 'Pitcher', :player_num =>2, :team_id => 3}])
Draft.create([{ :player_type => 'Pitcher', :player_num =>1, :team_id => 4}])
Draft.create([{ :player_type => 'Hitter', :player_num =>5, :team_id => 5}])
Draft.create([{ :player_type => 'Hitter', :player_num =>15, :team_id => 6}])
Draft.create([{ :player_type => 'Hitter', :player_num =>3, :team_id => 7}])
Draft.create([{ :player_type => 'Hitter', :player_num =>7, :team_id => 8}])
Draft.create([{ :player_type => 'Hitter', :player_num =>1, :team_id => 9}])

